"""Core primitives shared by every layer.

Contains the vocabulary (enums), the error types, the evidence model, hashing
and clock helpers, filesystem paths, typed configuration, and structured
logging. Nothing here imports a higher layer, so there are no cycles.
"""

from core.enums import (
    AnalysisSource,
    DocumentType,
    EvidenceSourceType,
    FactStatus,
    FieldType,
    ModelRunStatus,
    ModelRunTask,
    ResumeFileType,
    ResumeStatus,
    RiskLevel,
    SectionType,
    ValidationCode,
    ValidationSeverity,
)
from core.errors import (
    AIProviderError,
    AssistantError,
    ConfigurationError,
    DatabaseError,
    DuplicateResumeError,
    ImmutableFactError,
    MigrationError,
    MissingEvidenceError,
    ModelNotFoundError,
    ProfileNotFoundError,
    ProfilePersistenceError,
    ProfileValidationError,
    ProviderTimeoutError,
    ProviderUnavailableError,
    ResumeParseError,
    ResumeNotFoundError,
    ResumeValidationError,
    SafetyViolationError,
    SubmissionBlockedError,
)
from core.evidence import Evidence, Fact, FactValue
from core.hashing import (
    parse_iso_date,
    parse_iso_datetime,
    sha256_bytes,
    sha256_file,
    sha256_text,
    short_hash,
    utc_now,
)
from core.model_run import PROMPT_VERSION, ModelRun
from core.paths import Paths, get_paths, reset_paths
from core.settings import (
    AISettings,
    ApplicationSettings,
    AssistantSettings,
    BrowserSettings,
    DatabaseSettings,
    JobSearchSettings,
    LoggingSettings,
    SafetySettings,
    load_settings,
)

__all__ = [
    "AIProviderError",
    "AISettings",
    "AnalysisSource",
    "ApplicationSettings",
    "AssistantError",
    "AssistantSettings",
    "BrowserSettings",
    "ConfigurationError",
    "DatabaseError",
    "DatabaseSettings",
    "DocumentType",
    "DuplicateResumeError",
    "Evidence",
    "EvidenceSourceType",
    "Fact",
    "FactStatus",
    "FactValue",
    "FieldType",
    "ImmutableFactError",
    "JobSearchSettings",
    "LoggingSettings",
    "MigrationError",
    "MissingEvidenceError",
    "ModelNotFoundError",
    "ModelRun",
    "ModelRunStatus",
    "ModelRunTask",
    "PROMPT_VERSION",
    "Paths",
    "ProfileNotFoundError",
    "ProfilePersistenceError",
    "ProfileValidationError",
    "ProviderTimeoutError",
    "ProviderUnavailableError",
    "ResumeFileType",
    "ResumeNotFoundError",
    "ResumeParseError",
    "ResumeStatus",
    "ResumeValidationError",
    "RiskLevel",
    "SafetySettings",
    "SafetyViolationError",
    "SectionType",
    "SubmissionBlockedError",
    "ValidationCode",
    "ValidationSeverity",
    "get_paths",
    "load_settings",
    "parse_iso_date",
    "parse_iso_datetime",
    "reset_paths",
    "sha256_bytes",
    "sha256_file",
    "sha256_text",
    "short_hash",
    "utc_now",
]
